import {
    ArrowLeft,
    ArrowRight,
    Building,
    Calendar,
    Check,
    ChevronDown,
    CircleCheck,
    Clock,
    Hash,
    Info,
    KeyRound,
    LockKeyhole,
    Mail,
    MessageSquareText,
    Notebook,
    Pen,
    Plus,
    ShieldCheck,
    SlidersHorizontal,
    SquarePen,
    TextAlignJustify,
    Trash,
    TriangleAlert,
    UserPlus,
    UserRound,
    Users,
    X
} from "lucide-react";



export const LUCIDE_ICON_MAP = {
    Mail,
    password: LockKeyhole,
    X,
    ArrowRight,
    ArrowLeft,
    UserRound,
    Building,
    dropdown: ChevronDown,
    Info,
    ShieldCheck,
    KeyRound,
    Check,
    CircleCheck,
    UserPlus,
    Notebook,
    Plus,
    Hash,
    TextAlignJustify,
    action: SlidersHorizontal,
    EditBadge: SquarePen,
    Pen,
    Clock,
    Calendar,
    comment: MessageSquareText,
    warning: TriangleAlert,
    Trash,
    Users,
}